webtalk_init -webtalk_dir C:/Users/longt/Downloads/VLSI/Assignment/VLSI_Assignment/VLSI_Assignment.sim/sim_1/behav/xsim/xsim.dir/tb_RISC_FP_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu May  8 13:05:01 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "75b17aa6-7823-47e6-9060-46ffa0d56f28" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "54d558119b1443ed9f547002d8c59f2c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "321" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1425 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7748_KB" -context "xsim\\usage"
webtalk_transmit -clientid 190075323 -regid "" -xml C:/Users/longt/Downloads/VLSI/Assignment/VLSI_Assignment/VLSI_Assignment.sim/sim_1/behav/xsim/xsim.dir/tb_RISC_FP_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/longt/Downloads/VLSI/Assignment/VLSI_Assignment/VLSI_Assignment.sim/sim_1/behav/xsim/xsim.dir/tb_RISC_FP_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/longt/Downloads/VLSI/Assignment/VLSI_Assignment/VLSI_Assignment.sim/sim_1/behav/xsim/xsim.dir/tb_RISC_FP_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
